services:
  redis-master:
    build: .
    container_name: redis-master
    networks:
      - redis-net
    volumes:
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    build: .
    container_name: redis-slave1
    networks:
      - redis-net
    volumes:
      - redis-slave1-data:/data
    command: redis-server --port 6380 --slaveof redis-master 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master

  redis-slave2:
    build: .
    container_name: redis-slave2
    networks:
      - redis-net
    volumes:
      - redis-slave2-data:/data
    command: redis-server --port 6381 --slaveof redis-master 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master

  sentinel1:
    build: .
    container_name: redis-sentinel1
    networks:
      - redis-net
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel2:
    build: .
    container_name: redis-sentinel2
    networks:
      - redis-net
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel3:
    build: .
    container_name: redis-sentinel3
    networks:
      - redis-net
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

networks:
  redis-net:
    driver: bridge

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data: 