services:
  redis-master:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-slave1
    hostname: redis-slave1
    ports:
      - "6380:6380"
    networks:
      - redis-net
    volumes:
      - redis-slave1-data:/data
    command: redis-server --port 6380 --slaveof redis-master 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master

  redis-slave2:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-slave2
    hostname: redis-slave2
    ports:
      - "6381:6381"
    networks:
      - redis-net
    volumes:
      - redis-slave2-data:/data
    command: redis-server --port 6381 --slaveof redis-master 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master

  sentinel1:
    build:
      context: .
      dockerfile: Dockerfile.sentinel
    container_name: redis-sentinel1
    hostname: sentinel1
    ports:
      - "26379:26379"
    networks:
      - redis-net
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26379
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel2:
    build:
      context: .
      dockerfile: Dockerfile.sentinel
    container_name: redis-sentinel2
    hostname: sentinel2
    ports:
      - "26380:26379"
    networks:
      - redis-net
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26380
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel3:
    build:
      context: .
      dockerfile: Dockerfile.sentinel
    container_name: redis-sentinel3
    hostname: sentinel3
    ports:
      - "26381:26379"
    networks:
      - redis-net
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26381
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

networks:
  redis-net:
    driver: bridge

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data: 