services:
  redis-master:
    build: .
    container_name: redis-master
    network_mode: host
    volumes:
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    build: .
    container_name: redis-slave1
    network_mode: host
    volumes:
      - redis-slave1-data:/data
    command: redis-server --port 6380 --slaveof 127.0.0.1 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master

  redis-slave2:
    build: .
    container_name: redis-slave2
    network_mode: host
    volumes:
      - redis-slave2-data:/data
    command: redis-server --port 6381 --slaveof 127.0.0.1 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master

  sentinel1:
    build: .
    container_name: redis-sentinel1
    network_mode: host
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel2:
    build: .
    container_name: redis-sentinel2
    network_mode: host
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel3:
    build: .
    container_name: redis-sentinel3
    network_mode: host
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data: 