services:
  redis-master:
    build: .
    container_name: redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        aliases:
          - redis-master

  redis-slave1:
    build: .
    container_name: redis-slave1
    hostname: redis-slave1
    ports:
      - "6380:6380"
    volumes:
      - redis-slave1-data:/data
    command: redis-server --port 6380 --slaveof redis-master 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master
    networks:
      redis-net:
        aliases:
          - redis-slave1

  redis-slave2:
    build: .
    container_name: redis-slave2
    hostname: redis-slave2
    ports:
      - "6381:6381"
    volumes:
      - redis-slave2-data:/data
    command: redis-server --port 6381 --slaveof redis-master 6379 --requirepass bjtest123 --masterauth bjtest123
    depends_on:
      - redis-master
    networks:
      redis-net:
        aliases:
          - redis-slave2

  sentinel1:
    build: .
    container_name: redis-sentinel1
    hostname: sentinel1
    ports:
      - "26379:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      redis-net:
        aliases:
          - sentinel1

  sentinel2:
    build: .
    container_name: redis-sentinel2
    hostname: sentinel2
    ports:
      - "26380:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      redis-net:
        aliases:
          - sentinel2

  sentinel3:
    build: .
    container_name: redis-sentinel3
    hostname: sentinel3
    ports:
      - "26381:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      redis-net:
        aliases:
          - sentinel3

networks:
  redis-net:
    name: redis-net
    driver: bridge

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data: 