services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    hostname: redis-master
    network_mode: host
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    hostname: redis-slave1
    network_mode: host
    ports:
      - "6380:6380"
    volumes:
      - redis-slave1-data:/data
      - ./redis-slave1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    hostname: redis-slave2
    network_mode: host
    ports:
      - "6381:6381"
    volumes:
      - redis-slave2-data:/data
      - ./redis-slave2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master

  sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    hostname: sentinel1
    network_mode: host
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel2:
    image: redis:latest
    container_name: redis-sentinel2
    hostname: sentinel2
    network_mode: host
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel3:
    image: redis:latest
    container_name: redis-sentinel3
    hostname: sentinel3
    network_mode: host
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data: 